# Generated by Django 2.0.1 on 2018-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotplace', '0003_auto_20180307_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageInArticle',
            new_name='ArticleImage',
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
