# Generated by Django 2.0.3 on 2018-03-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schimcalculator', '0002_auto_20180328_1629'),
        ('dotplace', '0005_auto_20180314_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schimcalculator.Area'),
        ),
    ]
