# Generated by Django 2.0.3 on 2018-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schimcalculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='newsfeed',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='schim',
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
